########################################################################################################################
#                                                                                                                      #
#                                                       Language Detector                                              #
#                                             Written By: Alen_Alex (Semi-Vanilla Team)                                #
########################################################################################################################

auth:
  api-key: "57824c8884271b0f4fbfb0c48003e4f4"
  ssl: "true"

ignore-regex:
  -
