package com.semivanilla.languagedetector.enums;

import java.util.Arrays;

/**
 * This enums are specifically created for <i><detectlanguage's api/i>.
 * If in future, if you wish to change the languages, you should change this too!
 *
 * https://ws.detectlanguage.com/0.2/languages
 */

public enum Languages {
    AFAR("aa"),
    ABKHAZIAN("ab"),
    AFRIKAANS("af"),
    AKAN("ak"),
    AMHARIC("am"),
    ARABIC("ar"),
    ASSAMESE("as"),
    AYMARA("ay"),
    AZERBAIJANI("az"),
    BASHKIR("ba"),
    BELARUSIAN("be"),
    BULGARIAN("bg"),
    BIHARI("bh"),
    BISLAMA("bi"),
    BENGALI("bn"),
    TIBETAN("bo"),
    BRETON("br"),
    BOSNIAN("bs"),
    BUGINESE("bug"),
    CATALAN("ca"),
    CEBUANO("ceb"),
    CHEROKEE("chr"),
    CORSICAN("co"),
    SESELWA("crs"),
    CZECH("cs"),
    WELSH("cy"),
    DANISH("da"),
    GERMAN("de"),
    DHIVEHI("dv"),
    DZONGKHA("dz"),
    EGYPTIAN("egy"),
    GREEK("el"),
    ENGLISH("en"),
    ESPERANTO("eo"),
    SPANISH("es"),
    ESTONIAN("et"),
    BASQUE("eu"),
    PERSIAN("fa"),
    FINNISH("fi"),
    FIJIAN("fj"),
    FAROESE("fo"),
    FRENCH("fr"),
    FRISIAN("fy"),
    IRISH("ga"),
    SCOTS_GAELIC("gd"),
    GALICIAN("gl"),
    GUARANI("gn"),
    GOTHIC("got"),
    GUJARATI("gu"),
    MANX("gv"),
    HAUSA("ha"),
    HAWAIIAN("haw"),
    HINDI("hi"),
    HMONG("hmn"),
    CROATIAN("hr"),
    HAITIAN_CREOLE("ht"),
    HUNGARIAN("hu"),
    ARMENIAN("hy"),
    INTERLINGUA("ia"),
    INDONESIAN("id"),
    INTERLINGUE("ie"),
    IGBO("ig"),
    INUPIAK("ik"),
    ICELANDIC("is"),
    ITALIAN("it"),
    INUKTITUT("iu"),
    HEBREW("iw"),
    JAPANESE("ja"),
    JAVANESE("jw"),
    GEORGIAN("ka"),
    KHASI("kha"),
    KAZAKH("kk"),
    GREENLANDIC("kl"),
    KHMER("km"),
    KANNADA("kn"),
    KOREAN("ko"),
    KASHMIRI("ks"),
    KURDISH("ku"),
    KYRGYZ("ky"),
    LATIN("la"),
    LUXEMBOURGISH("lb"),
    GANDA("lg"),
    LIMBU("lif"),
    LINGALA("ln"),
    LAOTHIAN("lo"),
    LITHUANIAN("lt"),
    LATVIAN("lv"),
    MAURITIAN_CREOLE("mfe"),
    MALAGASY("mg"),
    MAORI("mi"),
    MACEDONIAN("mk"),
    MALAYALAM("ml"),
    MONGOLIAN("mn"),
    MARATHI("mr"),
    MALAY("ms"),
    MALTESE("mt"),
    BURMESE("my"),
    NAURU("na"),
    NEPALI("ne"),
    DUTCH("nl"),
    NORWEGIAN("no"),
    NDEBELE("nr"),
    PEDI("nso"),
    NYANJA("ny"),
    OCCITAN("oc"),
    OROMO("om"),
    ORIYA("or"),
    PUNJABI("pa"),
    POLISH("pl"),
    PASHTO("ps"),
    PORTUGUESE("pt"),
    QUECHUA("qu"),
    RHAETO_ROMANCE("rm"),
    RUNDI("rn"),
    ROMANIAN("ro"),
    RUSSIAN("ru"),
    KINYARWANDA("rw"),
    SANSKRIT("sa"),
    SCOTS("sco"),
    SINDHI("sd"),
    SANGO("sg"),
    SINHALESE("si"),
    SLOVAK("sk"),
    SLOVENIAN("sl"),
    SAMOAN("sm"),
    SHONA("sn"),
    SOMALI("so"),
    ALBANIAN("sq"),
    SERBIAN("sr"),
    SISWANT("ss"),
    SESOTHO("st"),
    SUNDANESE("su"),
    SWEDISH("sv"),
    SWAHILI("sw"),
    SYRIAC("syr"),
    TAMIL("ta"),
    TELUGU("te"),
    TAJIK("tg"),
    THAI("th"),
    TIGRINYA("ti"),
    TURKMEN("tk"),
    TAGALOG("tl"),
    KLINGON("tlh"),
    TSWANA("tn"),
    TONGA("to"),
    TURKISH("tr"),
    TSONGA("ts"),
    TATAR("tt"),
    UIGHUR("ug"),
    UKRAINIAN("uk"),
    URDU("ur"),
    UZBEK("uz"),
    VENDA("ve"),
    VIETNAMESE("vi"),
    VOLAPUK("vo"),
    WARAY_PHILIPPINES("war"),
    WOLOF("wo"),
    XHOSA("xh"),
    YIDDISH("yi"),
    YORUBA("yo"),
    ZHUANG("za"),
    CHINESE_SIMPLIFIED("zh"),
    CHINESE_TRADITIONAL("zh-Hant"),
    ZULU("zu"),


    ;

    private String language;

    Languages(String language) {
        this.language = language;
    }

    public String language(){
        return this.language;
    }
}
